In [1]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [2]:
np.arange(0,10)

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.random.rand(2)

array([0.26615765, 0.75525765])

In [12]:
np.random.rand(5,5)

array([[0.32391954, 0.05031776, 0.60833769, 0.06379027, 0.03227098],
       [0.44497294, 0.44539284, 0.744496  , 0.36589702, 0.5424658 ],
       [0.57708208, 0.70148599, 0.06987058, 0.28747471, 0.77554433],
       [0.6330782 , 0.93073625, 0.19415469, 0.48094885, 0.2739322 ],
       [0.44028145, 0.10503816, 0.10876602, 0.59429939, 0.48027064]])

In [13]:
np.random.randn(5,5)

array([[ 1.23924924,  2.36165875,  1.5602146 ,  0.60769755,  1.14873948],
       [ 0.99261065,  0.65008008,  1.61493727,  0.30898098, -0.09565925],
       [-0.51882311, -0.21069287, -0.07205761,  0.4449633 ,  0.30618065],
       [ 0.93218473, -0.91421016, -0.21764633, -0.55777242,  1.61841693],
       [ 0.5331988 , -1.75585664, -0.77615678, -0.10627931, -0.91009335]])

In [14]:
np.random.randint(1,100,10)

array([60, 12, 45, 38, 54, 18, 38,  1, 27, 30])